version: '3.8'
services:
  mongodb_container:
    container_name: mongo.local
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  employment_management_service:
    container_name: employment_management_service
    image: work_motion/employment_management:latest
    environment:
      SPRING_DATA_MONGODB_HOST: host.docker.internal
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container


volumes:
  mongodb_data_container:

networks:
  default:
    external:
      name: local-people-flow-network